---
- name: Set firewall default policy
  ufw: state=enabled policy=reject
  tags: ufw
#
# - name: Set ufw policy to deny all incoming connections
#   ufw: policy=deny direction=incoming
#   tags: ufw
#
# - name: Set ufw policy to allow all ougoing connections
#   ufw: policy=allow direction=outgoing
#   tags: ufw
  
- name: Allow ssh
  ufw: rule=allow port=22
  tags: ufw

- name: Allow nginx
  ufw: rule=allow port=80
  tags: ufw

- name: Allow nginx SSL
  ufw: rule=allow port=443
  tags: ufw

- name: Allow all access from RFC1918 networks to this host
  become: yes
  ufw:
    rule: allow
    src: '{{ item }}'
  with_items:
    - 10.0.0.0/8

- name: Allow all access from inventory hosts
  become: yes
  ufw:
    rule: allow
    src: '{{ item }}'
  with_items: "{{ groups['oldandnew'] | map('extract', hostvars, ['ansible_host']) }}"
  tags: ufwall

- name: Start ufw
  ufw: state=enabled
  tags: ufw
