version: '3'
services:
  postgres:
    image: postgres:9
    environment:
      - POSTGRES_USER=newsblur
      - POSTGRES_PASSWORD=newsblur
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - postgres_network
  redis:
    image: redis:3
    ports:
      - '6379:6379'
    volumes:
      - ../docker/volumes/redis:/data
      - ../config/redis.conf:/usr/local/etc/redis_server.conf
      - ../config/redis_docker.conf:/etc/redis_server.conf
      - ../docker/volumes/redis.var.lib:/var/lib/redis
    command: /usr/local/bin/redis-server /usr/local/etc/redis_server.conf
    networks:
      - redis_network
  
  mongo:
    image: mongo:3.2
    ports:
      - '27017:27017'
    command: mongod --smallfiles
    volumes:
      - ./docker/volumes/mongo:/data/db
    networks:
      - mongo_network



  elasticsearch:
    image: elasticsearch:1.7
    ports:
      - '9200:9200'
    volumes:
      - ./docker/volumes/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elasticsearch_network

  mongo:
    image: mongo:3.2
    ports:
      - '27017:27017'
    command: mongod --smallfiles
    volumes:
      - ./docker/volumes/mongo:/data/db
    networks:
      - mongo_network