---
- name: Ensure group "consul" exists
  become: true
  group:
    name: consul
    state: present

- name: Install Consul
  apt: 
    name: consul

- name: Create config file
  template:
    src: /srv/newsblur/consul/consul.json.j2
    dest: /consul.json
