---
- name: Ensure group "consul" exists
  become: true
  group:
    name: consul
    state: present

- name: Install Consul
  become: yes
  apt: 
    name: consul

- name: Ensure consul dir exists
  file:
    path: /srv/newsblur/consul
    state: directory

- name: Create config file
  template:
    src: consul.json.j2
    dest: /srv/newsblur/consul/consul.json
