---
# TODO: Close firewall and remove below line. Firewall should exclude all but known IPs.
- name: Allow consul-manager ports
  ufw: rule=allow port={{ item }}
  become: yes
  tags: ufw
  with_items:
    - "8300"
    - "8301"

- name: Ensure group "consul" exists
  become: true
  group:
    name: consul
    state: present

- name: Install Consul
  become: yes
  apt: 
    name: consul

