---
- name: Allow consul-manager ports
  ufw: rule=allow port={{ item }}
  become: yes
  tags: ufw
  with_items:
    - "8301"

- name: Ensure group "consul" exists
  become: true
  group:
    name: consul
    state: present

- name: Install Consul
  become: yes
  apt: 
    name: consul

###########
# Dnsmasq #
########### 

- name: Install Dnsmasq package
  become: yes
  apt:
    name: dnsmasq
    state: present

- name: Enable dnsmasq service
  become: yes
  service:
    name: dnsmasq
    enabled: true

- name: Bind dnsmasq to localhost
  become: yes
  lineinfile: dest=/etc/dnsmasq.conf state=present line='listen-address=127.0.0.1'

- name: Add localhost to resolv.conf
  become: yes
  lineinfile: dest=/etc/resolv.conf state=present line='nameserver 127.0.0.1' insertbefore=BOF

- name: user=root dnsmasq
  become: yes
  lineinfile: dest=/etc/dnsmasq.conf state=present line='user=root'

- name: Stop systemd-resolved
  become: yes
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
    masked: yes

- name: Launch dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: started

- name: Create Dnsmasq configuration
  become: yes
  template:
    src: dnsmasq-10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
