---
- name: Start monitor docker container
  become: yes
  docker_container:
    name: monitor
    image: newsblur/newsblur_python3
    env:
      DOCKERBUILD: "True"
    state: started
    command: bash -c "python /srv/newsblur/flask_monitor/db_monitor.py"
    ports:
      - 5000:5000
    restart_policy: unless-stopped
    volumes:
      - /srv/newsblur:/srv/newsblur

- name: Register monitor in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/monitor.json
  notify:
    - reload consul
