---

- name: Register haproxy in consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/haproxy.json
  notify:
    - reload consul

- name: Allow haproxy stats port
  ufw: rule=allow port={{ item }}
  become: yes
  tags: ufw
  with_items:
    - "1936"

- name: Template haproxy.cfg file
  template:
    src: /srv/newsblur/docker/haproxy/haproxy.consul.cfg.j2
    dest: /srv/newsblur/docker/haproxy/haproxy.consul.cfg
  register: updated_config

- name: Start HAProxy docker container
  become: yes
  docker_container:
    name: haproxy
    image: haproxy:latest
    env:
      DOCKERBUILD: "True"
    state: started
    network_mode: host # This exposes port 80
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    volumes:
      - /srv/newsblur:/srv/newsblur
      - /srv/newsblur/docker/haproxy/haproxy.consul.cfg:/usr/local/etc/haproxy/haproxy.cfg 
      - /etc/letsencrypt/live/newsblur.com:/etc/letsencrypt/live/newsblur.com
      - /etc/letsencrypt/archive/newsblur.com:/etc/letsencrypt/archive/newsblur.com

- name: Reload HAProxy configuration
  debug: 
    msg: Reloading HAProxy
  notify: reload haproxy
  changed_when: updated_config.changed
