---

- name: Start Consul Server
  vars:
    manager_ip: "167.172.142.207" # need to change this to use var from get_consul_manager_ip.py
  command: "consul agent -server -config-file=/consul.json --advertise {{ manager_ip }}"