---
# TODO: Close firewall and remove below line. Firewall should exclude all but known IPs.
- name: Allow consul-manager web ports
  ufw: rule=allow port={{ item }}
  become: yes
  tags: ufw
  with_items:
    - "8500"

- name: Register Manager IP
  script: /srv/newsblur/ansible/roles/consul/tasks/get_consul_manager_ip.py
  register: consul_manager_ip
  delegate_to: 127.0.0.1

- name: Create config file
  become: yes
  template:
    src: consul_manager.json.j2
    dest: /etc/consul.d/newsblur.json
  notify:
    - restart consul

- name: Start Consul
  become: yes
  service:
    name: consul
    state: started
    enabled: true
        