---
- name: Start nginx docker container
  become: yes
  docker_container:
    name: nginx
    image: nginx:1.19
    env:
      DOCKERBUILD: "True"
    state: started
    ports:
      - "80:80"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    expose:
      - "80"
    volumes:
      - /srv/newsblur/docker/nginx:/etc/nginx/conf.d
      - /srv/newsblur/:/srv/newsblur

- name: Register nginx in consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/nginx.json
  notify:
    - reload consul
