---
- hosts: app,node
  gather_facts: false
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml
  handlers:
    - include: roles/supervisor/handlers/main.yml

  tasks:
    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: dashboard3
      register: pulled
    
    - name: Reload gunicorn
      become: yes
      command: "docker kill --signal=HUP newsblur_web"
      when: pulled.changed and "app" in inventory_hostname
