---
- hosts: app,node
  remote_user: nb
  gather_facts: false
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml
  handlers:
    - include: roles/supervisor/handlers/main.yml

  tasks:
    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: dashboard3
