---
- hosts: NewsBlur_Docker
  remote_user: nb
  gather_facts: false
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml
  handlers:
    - include: roles/supervisor/handlers/main.yml

  tasks:
    - name: Deploy Web | Pull master from github
      git: repo={{ git_web_repo }} dest={{ goapp_gopath }}
      
    - name: Deploy Web | Pull secrets from github
      git: repo={{ git_secrets_repo }} dest={{ secrets_path }}
      
    - name: Deploy Web | Build turntouch-web
      environment: "{{ goapp_environment }}"
      shell: make build chdir={{ goapp_gopath }}
      
    - name: Deploy Web | Reload supervisor
      shell: supervisorctl reload
      become: yes
