---

- hosts: localhost
  connection: local
  remote_user: nb
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/droplet.yml
  
  tasks:
    - name: Defined role or name
      fail:
        msg: Please define a role for your new droplet
      when: role is not defined and name is not defined
    
    - name: Setting name from role using inventory
      set_fact:
        name: "{{ role }}"
      when: role is defined
      
    - name: Setting role from name
      set_fact:
        role: "{{ name | regex_replace('\\d+', '') }}"
      when: role is not defined

    - fail:
        msg: Please define a name for your new droplet
      when: name is not defined

    - name: Create a new droplet
      vars:
        token: "{{ lookup('file', '/srv/secrets-newsblur/keys/digital_ocean.token') | trim }}"
      community.digitalocean.digital_ocean_droplet:
        state: present
        name: "{{ name }}"
        size: "{{ droplet_size }}"
        region: "{{ droplet_region }}"
        image: "{{ droplet_image }}"
        wait_timeout: 500
        ssh_keys: [ "{{ droplet_ssh_key_id }}" ]
        unique_name: true
        oauth_token: "{{ token }}"
      register: created_droplet

    - debug:
        msg: "ID is {{ created_droplet.data.droplet.id }}, IP is {{ created_droplet.data.ip_address }}"

    - name: "Add to dyanmic inventory under {{ role }}"
      add_host:
        name: '{{ created_droplet.data.ip_address }}'
        group: '{{ role }}'
      
- name: Setup user on new machine
  include_playbook: setup_root.yml
