---
- name: Set up mongo db container
  hosts: db-mongo
  remote_user: nb
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - env_vars/base.yml
  
  roles:
    - base
    - docker
    - repo
    - mongo
    - client