---
- name: Set up redis server
  hosts: db_redis
  remote_user: nb
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - env_vars/base.yml
  roles:
    - base
    - docker
    - repo
    - {role: 'dnsmasq', tags: 'consul'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}
    - {role: 'redis', tags: 'redis'}
