---
- name: Set up task containers
  hosts: task
  remote_user: nb
  vars_files:
    - env_vars/base.yml
  vars:
    - update_apt_cache: yes
    - motd_role: task
  roles:
    - base
    - docker
    - repo
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}
    - celery_task
