---

- name: Set up node containers
  hosts: node
  remote_user: nb
  vars_files:
    - env_vars/base.yml
  vars:
    - update_apt_cache: yes
    - motd_role: app
  roles:
  - base
  - docker
  - repo
  - node

