---
- name: Setup elasticsearch container
  hosts: search
  remote_user: nb
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - env_vars/base.yml
  roles:
    - base
    - docker
    - repo
    - {role: 'consul', tags: 'consul'}
    - elasticsearch
    - consul-client
