---

- name: Set up task containers
  hosts: db_postgres
  remote_user: nb
  become: true
  vars_files:
    - env_vars/base.yml
  vars:
    - update_apt_cache: yes
    - motd_role: db
  roles:
    - base
    - docker
    - repo
    - {role: 'consul', tags: 'consul'}
    - postgres
    - consul-client
