---
- name: Set up redis containers
  hosts: db-redis-user
  remote_user: nb
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - env_vars/base.yml
  roles:
    - base
    - docker
    - repo
    - redis