---
- name: Set up redis containers
  hosts: db_redis
  remote_user: nb
  become: true
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - env_vars/base.yml
  roles:
    - base
    - docker
    - repo
    - redis
    - consul-client
