---

- name: Register Manager IP
  run_once: yes
  become: no
  register: consul_manager_ip
  local_action: command /srv/newsblur/ansible/roles/consul/tasks/get_consul_manager_ip.py

- name: Found consul manager IP
  debug:
    msg: "IP is {{ consul_manager_ip }}"
  
- name: Ensure /etc/consul.d exists
  become: yes
  file:
    path: /etc/consul.d
    state: directory

- name: Create config file
  become: yes
  template:
    src: consul.json.j2
    dest: /etc/consul.d/newsblur.json
  notify:
    - restart consul

- name: Start Consul
  become: yes
  service:
    name: consul
    state: started
    enabled: true
