---
# TODO
#- name: Register consul_manager_ip
#  become: yes
#  shell: python3 consul/get_consul_manager_ip.py
#  register: consul_manager_ip
- name: Start consul
  vars:
    join_addr: "167.172.142.207"
  command: "consul agent -config-file=/consul.json --join {{ join_addr }}"