---
- name: Register Manager IP
  script: /srv/newsblur/ansible/roles/consul/tasks/get_consul_manager_ip.py
  register: consul_manager_ip
  delegate_to: 127.0.0.1

- name: Start consul agent
  command: "consul agent -config-file=/srv/newsblur/consul/consul.json"
