---
- name: Start consul client Docker container
  become: yes
  #vars:
  #  JOIN_IP: $(ssh nb@{{lookup('file', '/srv/newsblur/consul/consul_manager_ip.txt')}} docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' consul-manager)
  docker_container:
    name: consul-client
    image: progrium/consul
    restart_policy: always
    state: started
    ports:
    - 8500:8500
    - 8400:8400
    - 8600:53/udp
    #command: "-join {{ JOIN_IP }}"
